using UnityEngine;

[RequireComponent(typeof(CharacterController))]
public class PlayerController : MonoBehaviour
{
    [SerializeField] private float speed = 5.5f; [SerializeField] private float sprintSpeed = 8f; [SerializeField] private float rotationSpeed = 12f; [SerializeField] private Transform ball; [SerializeField] private BallController ballController; [SerializeField] private Transform ballSocket; [SerializeField] private Transform enemyGoal; [SerializeField] private Transform[] passTargets; [SerializeField] private float controlRange = 2.2f; [SerializeField] private float shotPower = 14f; [SerializeField] private float passPower = 8f; [SerializeField] private PlayerAnimationController animationController;
    private CharacterController controller;
    private void Awake() { controller = GetComponent<CharacterController>(); if (animationController == null) animationController = GetComponentInChildren<PlayerAnimationController>(); }
    private void Update()
    {
        Vector2 input = MobileInput.Instance != null ? MobileInput.Instance.Move : new Vector2(Input.GetAxisRaw("Horizontal"), Input.GetAxisRaw("Vertical")); Vector3 direction = new Vector3(input.x, 0f, input.y); if (direction.sqrMagnitude > 1f) direction.Normalize(); bool sprint = MobileInput.Instance != null ? MobileInput.Instance.SprintHeld : Input.GetKey(KeyCode.LeftShift); controller.Move(direction * (sprint ? sprintSpeed : speed) * Time.deltaTime); if (direction.sqrMagnitude > .01f) transform.rotation = Quaternion.Slerp(transform.rotation, Quaternion.LookRotation(direction), rotationSpeed * Time.deltaTime); animationController?.SetLocomotion(direction.magnitude * (sprint ? 1f : .65f), sprint && direction.sqrMagnitude > .01f);
        if (ballController == null || ball == null || ballSocket == null) return; if (Vector3.Distance(transform.position, ball.position) <= controlRange && (ballController.Owner == null || ballController.Owner == transform)) ballController.TryControl(transform, ballSocket); bool pass = MobileInput.Instance != null ? MobileInput.Instance.ConsumePass() : Input.GetKeyDown(KeyCode.LeftControl); bool kick = false; float charge = 1f; BallController.ShotType type = BallController.ShotType.Ground; if (MobileInput.Instance != null) kick = MobileInput.Instance.ConsumeKick(out charge, out type); else if (Input.GetKeyDown(KeyCode.Space)) kick = true; if (ballController.Owner != transform) return; if (pass) { animationController?.PlayPass(); AudioManager.Instance?.PlayPass(); ballController.Pass(GetPassDirection(), passPower); } else if (kick) { animationController?.PlayKick(); AudioManager.Instance?.PlayKick(); CameraDirector.Instance?.ZoomForShot(); AudioManager.Instance?.Vibrate(.06f); ballController.Shoot((enemyGoal.position - ball.position).normalized, shotPower, type, charge); }
    }
    private Vector3 GetPassDirection() { Transform best = null; float scoreBest = float.MaxValue; if (passTargets != null) foreach (Transform target in passTargets) { if (target == null) continue; Vector3 delta = target.position - transform.position; float score = delta.magnitude - Vector3.Dot(transform.forward, delta.normalized) * 3f; if (score < scoreBest) { scoreBest = score; best = target; } } return best != null ? (best.position - ball.position).normalized : transform.forward; }
}
